### ISSUE TITLE
How to disable IR camera?

### ISSUE THREAD

**Issue by flymin** [kk1987/P52s-hackintosh#2]
I have a different laptop but with an IR camera. After i install Mojave 10.14.5, the IR camera seem to be used in the first hand. In some apps I can choose the source of camera input, but others can't. I have been suffering from the IR images for a long time. How did you exactly disable it?

**Comment by kk1987** [comment]
I think most if not all laptop cameras are USB devices, which you can disable via the SSDT config for USBInjectAll.kext.

Basically take these steps:
1. Find which USB port is the IR cam connected to. Follow "port discovery" section of https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/
2. Edit ACPI/dsl/SSDT-UIAC.dsl to remove that particular port's definition
3. Recompile the SSDT (e.g. by running update.sh under ACPI/dsl/) & install the updated SSDT-UIAC.aml

**Comment by flymin** [comment]
Thank you for your help. All work well!
